### ISSUE TITLE
Total file size?

### ISSUE THREAD

**Issue by rschmitty** [caarlos0/railscasts-downloader#3]
Do you have a rough idea of the total file size for free+pro videos?

**Comment by edomora97** [comment]
I've downloaded all the episodes in mp4.
- Free: 346 episodes = 6.1 GB
- Pro: 140 episodes = 4.9 GB (including revised ones)
- Total: 486 episodes = 11 GB

**Comment by caarlos0** [comment]
Neat! I'll add this to the README.
